version: '3.8'

services:
  postgres:
    container_name: postgres_container
    hostname: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  clickhouse:
    image: yandex/clickhouse-server
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  python-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-3.12-dev
    volumes:
      - ./:/app
#      - ./data:/app/data
    ports:
      - "3000:3000"
      - "8000:8000"
      - "8888:8888"  # For Jupyter if needed
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - DAGSTER_WEBSERVER_HOST=0.0.0.0
    stdin_open: true
    tty: true
    command: sleep infinity

volumes:
  postgres: